### ISSUE TITLE
Segmentation fault at Softmax

### ISSUE THREAD

**Issue by AmlanAlok** [codecolony/caffe#1]
@codecolony Hi Raghavendra,

This is regarding the issue on this website (https://github.com/alexgkendall/caffe-segnet/issues/43). I am new to caffe and I am facing the same problem that you did. I wanted to ask how exactly did you resolve the problem? Were exactly is the problem?

**Comment by codecolony** [comment]
Hi @AmlanAlok ,

The problem in my case was that I had some pixels unlabelled and there was no class for void. Hence the error. Hope this helps you.

**Comment by AmlanAlok** [comment]
@codecolony Thank you for responding.

I am new to caffe and I am having problem understanding how are pixels labelled in caffe and which part of the code is it ? I have made the following changes to the segnet_basic_train.prototext file.

layer {
  name: "conv_classifier"
  type: "Convolution"
  bottom: "conv_decode1"
  top: "conv_classifier"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    #num_output: 11                         # changed to 4
    **num_output: 4**
    kernel_size: 1
    weight_filler {
      type: "msra"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "conv_classifier"
  bottom: "label"
  top: "loss"
  softmax_param {engine: CAFFE}
  loss_param: {                                    
   weight_by_label_freqs: true
    #ignore_label: 11                                # changed to 4
    **ignore_label: 4**
    class_weighting: 0.2595
    class_weighting: 0.1826
    class_weighting: 4.5640
    class_weighting: 0.1417
    #class_weighting: 0.9051
    #class_weighting: 0.3826
    #class_weighting: 9.6446
    #class_weighting: 1.8418
    #class_weighting: 0.6823
    #class_weighting: 6.2478
    #class_weighting: 7.3614
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "conv_classifier"
  bottom: "label"
  top: "accuracy"
  top: "per_class_accuracy"
}

Please help me out.

**Comment by codecolony** [comment]
Can you show me your ground truth images? Are you sure all the pixels are labelled into one of the 4 classes?

**Comment by AmlanAlok** [comment]
@codecolony 

I understand what you are saying. I found some pixels which I have missed and did not account for. I will work on it and get back to you.

Thank you so much for pointing it out. It was very helpful.

**Comment by AmlanAlok** [comment]
@codecolony Hello again

I am now using 2 classes and the ground truth image is

![x1](https://cloud.githubusercontent.com/assets/26652299/24591144/12473ab2-1818-11e7-853d-d3998bb5a028.png)

I am still unable to fix the problem. I do realise there is some problem in my image, but I cannot find it. Can you please take a look at this image and tell me what do you think the problem could be?

**Comment by codecolony** [comment]
As I suspected, this way of representing ground truth images is wrong. Looks like you've used 0 and 255 to denote two classes. You have to use 0 and 1 instead. That will solve your problem.

**Comment by AmlanAlok** [comment]
@codecolony 

Yes! It absolutely does solve my problem. Thank you so much for your help.

**Comment by codecolony** [comment]
Great!
